var letterOrderData = [{
   //---------------------------------Stand 4 on 5
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "A",
   "variant-id" : "746995109",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "B",
   "variant-id" : "746995197",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "C",
   "variant-id" : "746995281",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "D",
   "variant-id" : "746995369",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "E",
   "variant-id" : "746995453",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "F",
   "variant-id" : "746995549",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "G",
   "variant-id" : "746995633",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "H",
   "variant-id" : "746995737",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "I",
   "variant-id" : "746995837",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "J",
   "variant-id" : "746995929",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "K",
   "variant-id" : "746996021",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "L",
   "variant-id" : "746996117",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "M",
   "variant-id" : "746996201",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "N",
   "variant-id" : "746996289",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "O",
   "variant-id" : "746996369",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "P",
   "variant-id" : "746996461",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "Q",
   "variant-id" : "746996545",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "R",
   "variant-id" : "746996637",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "S",
   "variant-id" : "746996737",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "T",
   "variant-id" : "746996833",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "U",
   "variant-id" : "746996917",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "V",
   "variant-id" : "746997005",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "W",
   "variant-id" : "746997101",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "X",
   "variant-id" : "746997185",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "Y",
   "variant-id" : "746997265",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "Z",
   "variant-id" : "746997349",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "0",
   "variant-id" : "746991737",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "1",
   "variant-id" : "746991821",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "2",
   "variant-id" : "746991901",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "3",
   "variant-id" : "746991989",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "4",
   "variant-id" : "746992093",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "5",
   "variant-id" : "746992193",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "6",
   "variant-id" : "746992281",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "7",
   "variant-id" : "746992373",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "8",
   "variant-id" : "746992473",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "9",
   "variant-id" : "746992565",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "&",
   "variant-id" : "746992909",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "'",
   "variant-id" : "746993229",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "¢",
   "variant-id" : "746992649",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : ":",
   "variant-id" : "746993501",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : ",",
   "variant-id" : "746993313",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "-",
   "variant-id" : "746993857",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "$",
   "variant-id" : "746992737",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "!",
   "variant-id" : "746993009",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "(",
   "variant-id" : "746994233",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "“",
   "variant-id" : "746993581",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "%",
   "variant-id" : "746994149",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : ".",
   "variant-id" : "746992825",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : ")",
   "variant-id" : "746994321",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "rightquote",
   "variant-id" : "746993677",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : ";",
   "variant-id" : "746993401",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "/",
   "variant-id" : "746993761",
   },
   {
   "style"      : "stand",
   "size"       : "4 on 5",
   "char"       : "?",
   "variant-id" : "746993153",
   },//---------------------------------Stand 6 on 7
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "A",
   "variant-id" : "746995133",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "B",
   "variant-id" : "746995217",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "C",
   "variant-id" : "746995305",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "D",
   "variant-id" : "746995389",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "E",
   "variant-id" : "746995477",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "F",
   "variant-id" : "746995573",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "G",
   "variant-id" : "746995657",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "H",
   "variant-id" : "746995761",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "I",
   "variant-id" : "746995861",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "J",
   "variant-id" : "746995953",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "K",
   "variant-id" : "746996045",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "L",
   "variant-id" : "746996137",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "M",
   "variant-id" : "746996225",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "N",
   "variant-id" : "746996309",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "O",
   "variant-id" : "746996393",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "P",
   "variant-id" : "746996481",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "Q",
   "variant-id" : "746996565",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "R",
   "variant-id" : "746996657",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "S",
   "variant-id" : "746996761",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "T",
   "variant-id" : "746996857",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "U",
   "variant-id" : "746996937",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "V",
   "variant-id" : "746997025",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "W",
   "variant-id" : "746997121",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "X",
   "variant-id" : "746997205",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "Y",
   "variant-id" : "746997285",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "Z",
   "variant-id" : "746997369",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "0",
   "variant-id" : "746991761",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "1",
   "variant-id" : "746991841",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "2",
   "variant-id" : "746991925",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "3",
   "variant-id" : "746992009",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "4",
   "variant-id" : "746992117",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "5",
   "variant-id" : "746992217",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "6",
   "variant-id" : "746992305",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "7",
   "variant-id" : "746992401",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "8",
   "variant-id" : "746992501",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "9",
   "variant-id" : "746992585",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "&",
   "variant-id" : "746992929",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "'",
   "variant-id" : "746993249",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "¢",
   "variant-id" : "746992669",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : ":",
   "variant-id" : "746993521",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : ",",
   "variant-id" : "746993333",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "-",
   "variant-id" : "746993877",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "$",
   "variant-id" : "746992757",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "!",
   "variant-id" : "746993029",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "(",
   "variant-id" : "746994257",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "“",
   "variant-id" : "746993605",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "%",
   "variant-id" : "746994173",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : ".",
   "variant-id" : "746992849",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : ")",
   "variant-id" : "746994361",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "rightquote",
   "variant-id" : "746993701",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : ";",
   "variant-id" : "746993421",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "/",
   "variant-id" : "746993785",
   },
   {
   "style"      : "stand",
   "size"       : "6 on 7",
   "char"       : "?",
   "variant-id" : "746993173",
   },//---------------------------------Stand 8 on 10
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "A",
   "variant-id" : "746995165",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "B",
   "variant-id" : "746995249",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "C",
   "variant-id" : "746995341",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "D",
   "variant-id" : "746995425",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "E",
   "variant-id" : "746995521",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "F",
   "variant-id" : "746995605",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "G",
   "variant-id" : "746995693",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "H",
   "variant-id" : "746995793",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "I",
   "variant-id" : "746995893",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "J",
   "variant-id" : "746995993",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "K",
   "variant-id" : "746996081",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "L",
   "variant-id" : "746996169",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "M",
   "variant-id" : "746996257",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "N",
   "variant-id" : "746996345",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "O",
   "variant-id" : "746996429",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "P",
   "variant-id" : "746996517",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "Q",
   "variant-id" : "746996601",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "R",
   "variant-id" : "746996693",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "S",
   "variant-id" : "746996797",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "T",
   "variant-id" : "746996889",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "U",
   "variant-id" : "746996977",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "V",
   "variant-id" : "746997061",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "W",
   "variant-id" : "746997157",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "X",
   "variant-id" : "746997237",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "Y",
   "variant-id" : "746997317",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "Z",
   "variant-id" : "746997401",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "0",
   "variant-id" : "746991793",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "1",
   "variant-id" : "746991873",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "2",
   "variant-id" : "746991961",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "3",
   "variant-id" : "746992049",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "4",
   "variant-id" : "746992157",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "5",
   "variant-id" : "746992249",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "6",
   "variant-id" : "746992341",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "7",
   "variant-id" : "746992441",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "8",
   "variant-id" : "746992533",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "9",
   "variant-id" : "746992621",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "&",
   "variant-id" : "746992977",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "'",
   "variant-id" : "746993289",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "¢",
   "variant-id" : "746992713",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : ":",
   "variant-id" : "746993557",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : ",",
   "variant-id" : "746993365",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "-",
   "variant-id" : "746993925",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "$",
   "variant-id" : "746992793",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "!",
   "variant-id" : "746993081",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "(",
   "variant-id" : "746994293",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "“",
   "variant-id" : "746993645",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "%",
   "variant-id" : "746994205",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : ".",
   "variant-id" : "746992881",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : ")",
   "variant-id" : "746994405",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "rightquote",
   "variant-id" : "746993733",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : ";",
   "variant-id" : "746993465",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "/",
   "variant-id" : "746993821",
   },
   {
   "style"      : "stand",
   "size"       : "8 on 10",
   "char"       : "?",
   "variant-id" : "746993205",
   },//---------------------------------Cond 4 on 5
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "A",
   "variant-id" : "746650905",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "B",
   "variant-id" : "746650977",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "C",
   "variant-id" : "746651057",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "D",
   "variant-id" : "746651241",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "E",
   "variant-id" : "746651313",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "F",
   "variant-id" : "746651397",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "G",
   "variant-id" : "746651581",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "H",
   "variant-id" : "746651661",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "I",
   "variant-id" : "746651741",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "J",
   "variant-id" : "746651869",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "K",
   "variant-id" : "746652001",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "L",
   "variant-id" : "746652073",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "M",
   "variant-id" : "746652145",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "N",
   "variant-id" : "746652245",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "O",
   "variant-id" : "746652329",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "P",
   "variant-id" : "746652409",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "Q",
   "variant-id" : "746652513",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "R",
   "variant-id" : "746652605",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "S",
   "variant-id" : "746652793",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "T",
   "variant-id" : "746649217",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "U",
   "variant-id" : "746653061",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "V",
   "variant-id" : "746653145",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "W",
   "variant-id" : "746653221",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "X",
   "variant-id" : "746653413",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "Y",
   "variant-id" : "746653497",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "Z",
   "variant-id" : "746653569",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "0",
   "variant-id" : "746647789",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "1",
   "variant-id" : "746647877",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "2",
   "variant-id" : "746647949",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "3",
   "variant-id" : "746648017",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "4",
   "variant-id" : "746648097",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "5",
   "variant-id" : "746648177",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "6",
   "variant-id" : "746648257",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "7",
   "variant-id" : "746648337",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "8",
   "variant-id" : "746648421",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "9",
   "variant-id" : "746648501",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "&",
   "variant-id" : "746648817",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "'",
   "variant-id" : "746649057",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "¢",
   "variant-id" : "746648577",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : ":",
   "variant-id" : "746649289",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : ",",
   "variant-id" : "746649145",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "-",
   "variant-id" : "746649621",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "$",
   "variant-id" : "746648653",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "!",
   "variant-id" : "746648897",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "(",
   "variant-id" : "746649945",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "“",
   "variant-id" : "746649381",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "%",
   "variant-id" : "746649869",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : ".",
   "variant-id" : "746648729",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : ")",
   "variant-id" : "746650041",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "”",
   "variant-id" : "746649461",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : ";",
   "variant-id" : "746649217",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "/",
   "variant-id" : "746649541",
   },
   {
   "style"      : "cond",
   "size"       : "4 on 5",
   "char"       : "?",
   "variant-id" : "746648969",
   },//---------------------------------Cond 6 on 7
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "A",
   "variant-id" : "746650925",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "B",
   "variant-id" : "746650997",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "C",
   "variant-id" : "746651109",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "D",
   "variant-id" : "746651261",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "E",
   "variant-id" : "746651337",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "F",
   "variant-id" : "746651421",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "G",
   "variant-id" : "746651609",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "H",
   "variant-id" : "746651689",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "I",
   "variant-id" : "746651761",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "J",
   "variant-id" : "746651933",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "K",
   "variant-id" : "746652025",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "L",
   "variant-id" : "746652097",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "M",
   "variant-id" : "746652169",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "N",
   "variant-id" : "746652269",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "O",
   "variant-id" : "746652353",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "P",
   "variant-id" : "746652429",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "Q",
   "variant-id" : "746652553",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "R",
   "variant-id" : "746652625",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "S",
   "variant-id" : "746652813",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "T",
   "variant-id" : "746649237",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "U",
   "variant-id" : "746653089",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "V",
   "variant-id" : "746653165",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "W",
   "variant-id" : "746653241",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "X",
   "variant-id" : "746653433",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "Y",
   "variant-id" : "746653517",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "Z",
   "variant-id" : "746653589",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "0",
   "variant-id" : "746647809",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "1",
   "variant-id" : "746647901",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "2",
   "variant-id" : "746647969",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "3",
   "variant-id" : "746648049",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "4",
   "variant-id" : "746648117",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "5",
   "variant-id" : "746648201",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "6",
   "variant-id" : "746648281",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "7",
   "variant-id" : "746648361",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "8",
   "variant-id" : "746648445",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "9",
   "variant-id" : "746648545",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "&",
   "variant-id" : "746648837",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "'",
   "variant-id" : "746649085",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "¢",
   "variant-id" : "746648597",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : ":",
   "variant-id" : "746649313",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : ",",
   "variant-id" : "746649165",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "-",
   "variant-id" : "746649641",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "$",
   "variant-id" : "746648673",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "!",
   "variant-id" : "746648917",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "(",
   "variant-id" : "746649965",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "“",
   "variant-id" : "746649401",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "%",
   "variant-id" : "746649893",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : ".",
   "variant-id" : "746648757",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : ")",
   "variant-id" : "746650061",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "”",
   "variant-id" : "746649485",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : ";",
   "variant-id" : "746649237",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "/",
   "variant-id" : "746649561",
   },
   {
   "style"      : "cond",
   "size"       : "6 on 7",
   "char"       : "?",
   "variant-id" : "746648993",
   },//---------------------------------Cond 8 on 10
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "A",
   "variant-id" : "746650949",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "B",
   "variant-id" : "746651025",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "C",
   "variant-id" : "746651173",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "D",
   "variant-id" : "746651285",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "E",
   "variant-id" : "746651373",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "F",
   "variant-id" : "746651449",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "G",
   "variant-id" : "746651633",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "H",
   "variant-id" : "746651713",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "I",
   "variant-id" : "746651761",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "J",
   "variant-id" : "746651969",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "K",
   "variant-id" : "746652049",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "L",
   "variant-id" : "746652121",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "M",
   "variant-id" : "746652201",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "N",
   "variant-id" : "746652297",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "O",
   "variant-id" : "746652377",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "P",
   "variant-id" : "746652473",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "Q",
   "variant-id" : "746652581",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "R",
   "variant-id" : "746652669",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "S",
   "variant-id" : "746652837",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "T",
   "variant-id" : "746649261",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "U",
   "variant-id" : "746653113",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "V",
   "variant-id" : "746653193",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "W",
   "variant-id" : "746653289",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "X",
   "variant-id" : "746653433",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "Y",
   "variant-id" : "746653541",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "Z",
   "variant-id" : "746653657",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "0",
   "variant-id" : "746647833",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "1",
   "variant-id" : "746647925",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "2",
   "variant-id" : "746647993",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "3",
   "variant-id" : "746648073",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "4",
   "variant-id" : "746648145",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "5",
   "variant-id" : "746648229",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "6",
   "variant-id" : "746648305",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "7",
   "variant-id" : "746648389",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "8",
   "variant-id" : "746648469",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "9",
   "variant-id" : "746648545",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "&",
   "variant-id" : "746648861",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "'",
   "variant-id" : "746649117",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "¢",
   "variant-id" : "746648621",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : ":",
   "variant-id" : "746649341",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : ",",
   "variant-id" : "746649193",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "-",
   "variant-id" : "746649669",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "$",
   "variant-id" : "746648697",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "!",
   "variant-id" : "746648941",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "(",
   "variant-id" : "746650009",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "“",
   "variant-id" : "746649429",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "%",
   "variant-id" : "746649917",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : ".",
   "variant-id" : "746648785",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : ")",
   "variant-id" : "746650089",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "”",
   "variant-id" : "746649509",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : ";",
   "variant-id" : "746649261",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "/",
   "variant-id" : "746649593",
   },
   {
   "style"      : "cond",
   "size"       : "8 on 10",
   "char"       : "?",
   "variant-id" : "746649017",
   },//---------------------------------Mod 4 on 5
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "A",
   "variant-id" : "796631637",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "B",
   "variant-id" : "796631773",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "C",
   "variant-id" : "796631873",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "D",
   "variant-id" : "796631973",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "E",
   "variant-id" : "796632077",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "F",
   "variant-id" : "796632205",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "G",
   "variant-id" : "796632309",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "H",
   "variant-id" : "796632413",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "I",
   "variant-id" : "796632521",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "J",
   "variant-id" : "796632665",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "K",
   "variant-id" : "796632765",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "L",
   "variant-id" : "796632897",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "M",
   "variant-id" : "796633001",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "N",
   "variant-id" : "796633101",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "O",
   "variant-id" : "796633225",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "P",
   "variant-id" : "796633329",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "Q",
   "variant-id" : "796633465",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "R",
   "variant-id" : "796633581",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "S",
   "variant-id" : "796633681",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "T",
   "variant-id" : "796633805",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "U",
   "variant-id" : "796633909",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "V",
   "variant-id" : "796634089",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "W",
   "variant-id" : "796634185",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "X",
   "variant-id" : "796634301",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "Y",
   "variant-id" : "796634409",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "Z",
   "variant-id" : "796634517",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "0",
   "variant-id" : "796627249",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "1",
   "variant-id" : "796627357",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "2",
   "variant-id" : "796627493",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "3",
   "variant-id" : "796627613",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "4",
   "variant-id" : "796627721",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "5",
   "variant-id" : "796627821",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "6",
   "variant-id" : "796627921",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "7",
   "variant-id" : "796628029",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "8",
   "variant-id" : "796628137",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "9",
   "variant-id" : "796628257",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "&",
   "variant-id" : "796628713",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "'",
   "variant-id" : "796629197",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "¢",
   "variant-id" : "796628357",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : ":",
   "variant-id" : "796629537",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : ",",
   "variant-id" : "796629309",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "-",
   "variant-id" : "796629989",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "$",
   "variant-id" : "796628469",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "!",
   "variant-id" : "796628949",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "(",
   "variant-id" : "796630517",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "“",
   "variant-id" : "796629637",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "%",
   "variant-id" : "796630417",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : ".",
   "variant-id" : "796628605",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : ")",
   "variant-id" : "746994321",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "”",
   "variant-id" : "796629749",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : ";",
   "variant-id" : "796629433",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "/",
   "variant-id" : "796629881",
   },
   {
   "style"      : "mod",
   "size"       : "4 on 5",
   "char"       : "?",
   "variant-id" : "796629077",
   },//---------------------------------Mod 6 on 7
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "A",
   "variant-id" : "796631657",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "B",
   "variant-id" : "796631793",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "C",
   "variant-id" : "796631893",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "D",
   "variant-id" : "796631993",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "E",
   "variant-id" : "796632097",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "F",
   "variant-id" : "796632225",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "G",
   "variant-id" : "796632329",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "H",
   "variant-id" : "796632437",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "I",
   "variant-id" : "796632541",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "J",
   "variant-id" : "796632685",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "K",
   "variant-id" : "796632785",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "L",
   "variant-id" : "796632917",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "M",
   "variant-id" : "796633021",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "N",
   "variant-id" : "796633125",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "O",
   "variant-id" : "796633225",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "P",
   "variant-id" : "796633365",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "Q",
   "variant-id" : "796633485",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "R",
   "variant-id" : "796633601",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "S",
   "variant-id" : "796633701",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "T",
   "variant-id" : "796633825",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "U",
   "variant-id" : "796633929",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "V",
   "variant-id" : "796634109",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "W",
   "variant-id" : "796634205",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "X",
   "variant-id" : "796634321",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "Y",
   "variant-id" : "796634429",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "Z",
   "variant-id" : "796634561",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "0",
   "variant-id" : "796627269",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "1",
   "variant-id" : "796627377",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "2",
   "variant-id" : "796627513",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "3",
   "variant-id" : "796627633",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "4",
   "variant-id" : "796627741",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "5",
   "variant-id" : "796627841",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "6",
   "variant-id" : "796627941",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "7",
   "variant-id" : "796628049",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "8",
   "variant-id" : "796628169",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "9",
   "variant-id" : "796628277",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "&",
   "variant-id" : "796628733",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "'",
   "variant-id" : "796629217",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "¢",
   "variant-id" : "796628385",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : ":",
   "variant-id" : "796629557",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : ",",
   "variant-id" : "796629329",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "-",
   "variant-id" : "796630009",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "$",
   "variant-id" : "796628513",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "!",
   "variant-id" : "796628985",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "(",
   "variant-id" : "796630537",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "“",
   "variant-id" : "796629657",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "%",
   "variant-id" : "796630437",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : ".",
   "variant-id" : "796628625",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : ")",
   "variant-id" : "746994361",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "”",
   "variant-id" : "796629773",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : ";",
   "variant-id" : "796629453",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "/",
   "variant-id" : "796629901",
   },
   {
   "style"      : "mod",
   "size"       : "6 on 7",
   "char"       : "?",
   "variant-id" : "796629097",
   },//---------------------------------Mod 8 on 10
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "A",
   "variant-id" : "796631693",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "B",
   "variant-id" : "796631821",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "C",
   "variant-id" : "796631921",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "D",
   "variant-id" : "796632025",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "E",
   "variant-id" : "796632125",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "F",
   "variant-id" : "796632257",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "G",
   "variant-id" : "796632357",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "H",
   "variant-id" : "796632469",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "I",
   "variant-id" : "796632589",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "J",
   "variant-id" : "796632713",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "K",
   "variant-id" : "796632817",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "L",
   "variant-id" : "796632953",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "M",
   "variant-id" : "796633053",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "N",
   "variant-id" : "796633145",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "O",
   "variant-id" : "796633273",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "P",
   "variant-id" : "796633405",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "Q",
   "variant-id" : "796633513",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "R",
   "variant-id" : "796633633",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "S",
   "variant-id" : "796633733",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "T",
   "variant-id" : "796633853",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "U",
   "variant-id" : "796633961",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "V",
   "variant-id" : "796634137",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "W",
   "variant-id" : "796634245",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "X",
   "variant-id" : "796634353",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "Y",
   "variant-id" : "796634457",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "Z",
   "variant-id" : "796634593",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "0",
   "variant-id" : "796627297",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "1",
   "variant-id" : "796627405",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "2",
   "variant-id" : "796627541",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "3",
   "variant-id" : "796627669",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "4",
   "variant-id" : "796627769",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "5",
   "variant-id" : "796627869",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "6",
   "variant-id" : "796627973",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "7",
   "variant-id" : "796628077",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "8",
   "variant-id" : "796628197",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "9",
   "variant-id" : "796628305",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "&",
   "variant-id" : "796628769",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "'",
   "variant-id" : "796629249",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "¢",
   "variant-id" : "796628413",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : ":",
   "variant-id" : "796629585",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : ",",
   "variant-id" : "796629361",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "-",
   "variant-id" : "796630045",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "$",
   "variant-id" : "796628541",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "!",
   "variant-id" : "796629017",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "(",
   "variant-id" : "796630565",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "“",
   "variant-id" : "796629685",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "%",
   "variant-id" : "796630465",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : ".",
   "variant-id" : "796628653",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : ")",
   "variant-id" : "746994405",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "”",
   "variant-id" : "796629805",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : ";",
   "variant-id" : "796629489",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "/",
   "variant-id" : "796629929",
   },
   {
   "style"      : "mod",
   "size"       : "8 on 10",
   "char"       : "?",
   "variant-id" : "796629133",
   },
]












